# Generated by Django 2.2.5 on 2022-08-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='description',
            field=models.CharField(default='RideDescription', max_length=999),
        ),
        migrations.AlterField(
            model_name='ride',
            name='difficulty',
            field=models.CharField(choices=[('Easy', '1'), ('Medium', '2'), ('Hard', '3'), ('Very Hard', '4'), ('Nightmare', '5')], max_length=10),
        ),
    ]
