# Generated by Django 2.2.5 on 2022-08-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220812_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Road Bike', 'RB'), ('Mountain Bike', 'MB'), ('Hike', 'H')], max_length=10)),
                ('length', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', '1'), ('Medium', '2'), ('Hard', '3'), ('Very Hard', '4'), ('Nightmare', '5')], max_length=10)),
                ('description', models.CharField(default='', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', '1'), ('Medium', '2'), ('Hard', '3'), ('Very Hard', '4'), ('Nightmare', '5')], max_length=10)),
                ('description', models.CharField(default='', max_length=999)),
            ],
        ),
        migrations.AlterField(
            model_name='ride',
            name='description',
            field=models.CharField(default='', max_length=999),
        ),
    ]
