# Generated by Django 2.2.5 on 2022-08-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220820_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hike',
        ),
    ]
