# Generated by Django 2.2.5 on 2022-08-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_hike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activity',
        ),
    ]
