# Generated by Django 2.2.5 on 2022-08-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ride',
        ),
    ]
